# Generated by Django 4.1.5 on 2023-01-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('discount', models.BooleanField()),
                ('duration', models.DateTimeField(auto_now=True)),
                ('authorName', models.CharField(max_length=50)),
            ],
        ),
    ]
